---
# tasks file for docker
- include_tasks: docker_ubuntu.yml
  when: ansible_os_family == "Debian"
  tags:
    - unbound

- include_tasks: docker_centos.yml
  when: ansible_os_family == "RedHat"
  tags:
    - unbound

